services:
  - type: web
    name: node-red
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node-red
    envVars:
      - key: NODE_RED_ENABLE_PROJECTS
        value: 'true'
